# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Generate derived files
      run: make -f derived.mk

    - name: Push derived files
      run: |
        git status --short rfc2629-no-doctype.xslt | fgrep -s " M " || exit 0
        git config --global user.name "Julian's HTML Bot"
        git config --global user.email "julian.reschke@gmx.de"
        git commit -m "generated files" rfc2629-no-doctype.xslt
        git push
